### ISSUE TITLE
Asking for resources using azure-classic returns "not found" response

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-ai#21]
### What happened?

I asked for an “app service using azure classic provider” and was told:

```
I see that your goal is to create an app service using the Azure classic provider. However, I must inform you that as a Pulumi AI assistant, I can only create programs using resources returned by the Pulumi Registry, and the registry results don't have Azure Classic provider resources.
```

### Expected Behavior

It should provide output based on the azure-classic provider

### Steps to reproduce

Go to pulumi ai and ask:
"app service using azure classic provider"

See that it returns message that it can't.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
We should ensure that the AI *can* produce Azure Classic responses, but that it (lightly) prefers Azure Native.

**Comment by tusharshahrs** [comment]
Here is another repro:  https://www.pulumi.com/ai/?convid=0b21a5dc-05a6-457e-a551-eedb99ad4a81
