### ISSUE TITLE
Markdown copy buttons are inconsistent

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-ai#34]
### What happened?

<img width="625" alt="Screenshot 2023-06-15 at 4 01 01 PM" src="https://github.com/pulumi/pulumi-ai/assets/22222529/8376fecc-6f95-4d38-ac5b-3f748d00e036">

We have two copy buttons for markdown (looking) block text. They render differently.

### Expected Behavior

Graphics appear cohesive and unified.

### Steps to reproduce

See https://www.pulumi.com/ai/?convid=5001ca10-f900-49f2-9d58-308384e1ef39.

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
I agree the buttons should be the same. Also the copy button with text "Copy" triggers the hover effect around the edges where the button is not yet clickable. So you see the the hover effect and you click but nothing happens.

**Comment by AaronFriel** [comment]
@Zaid-Ajaj it looks like we've likely fixed the rendering bug with the copy button and the copy behavior - only the button itself is clickable, shows the correct cursor, and causes text to be copied.
