### ISSUE TITLE
Add context history for resuming conversations with Pulumi AI

### ISSUE THREAD

**Issue by s0phr0syn3** [pulumi/pulumi-ai#35]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be amazing to have history to be able to continue working with Pulumi AI via the web client after it has disconnected. Reconnecting via the link beneath the chatbox reloads the whole page, which causes all context from the existing conversation to be lost. Being able to retain that context to continue working on a Pulumi project which is not yet complete would be very helpful vs having to start over.

Apologies if this has been requested already -- I didn't see this specific request in issues.

**Comment by AaronFriel** [comment]
Hey @s0phr0syn3, we've revamped the Pulumi AI web application and it no longer relies on that persistent connection. You should be able to resume conversations (including previous conversations you've saved the links to!) and build on those programs.
