### ISSUE TITLE
Pulumi AI doesn't use typed properties all the time

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-ai#36]
### What happened?

Pulumi AI most often uses untyped dicts in Python, however sometimes if you push it, it will use the typed properties

### Expected Behavior

Pulumi AI in python should use typed properties

### Steps to reproduce

If I ask Pulumi AI to create something in datadog, say:

> Create datadog custom pipeline with an attribute processor.

It will use an untyped dict.

If I explicitly ask it to use properties, say:

> Create a Datadog attribute processor and then add it to a custom pipeline

Sometimes it creates the resource with the properties, sometimes it doesn't

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
It now consistently uses classes.  E.g.
* https://www.pulumi.com/ai/conversations/62673bbb-5977-4fe8-9a06-ed2f63142190
* https://www.pulumi.com/ai/conversations/64cce462-a4e0-4842-8d5d-1086daac1734
