### ISSUE TITLE
Option to share conversation missing in Safari on macOS

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi-ai#46]
### What happened?

I went to the Pulumi AI site to test something with the intent of sharing the conversation with a community user. However, I found that the "Share Conversation" button was missing from the site when the site is viewed in Safari on macOS.

### Expected Behavior

I expected to be able to use the "Share Conversation" link when using Safari on macOS.

### Steps to reproduce

1. Visit pulumi.com/ai using Safari on macOS.
2. Enter a prompt.
3. After Pulumi AI has finished responding, look for the "Share Conversation" button. It will be missing.
4. Repeat in either Firefox or Chrome, and note the ability to share the conversation is present.

### Output of `pulumi about`

`pulumi about` won't be relevant for this issue, but here are the macOS and Safari versions used when encountering this behavior:

Mac OS Ventura 13.4.1
Safari 16.5.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
@scottslowe @cnunciato is this still occurring on the refreshed site (since 2 weeks ago)?

**Comment by scottslowe** [comment]
@AaronFriel Yes (I just checked).

**Comment by cnunciato** [comment]
Interesting -- I see it (Safari 16.5.2): 

![image](https://github.com/pulumi/pulumi-ai/assets/274700/0c47ad9e-ba40-4842-bcb7-9a6e9079c311)

Note that you won't see it unless you're on a conversation page (so if you're starting a brand-new conversation, you'll have to submit something first). So you don't see a share link on this page @scottslowe?

https://www.pulumi.com/ai/conversations/3277f26b-8aad-4321-90b7-4c9a89b13b80

**Comment by scottslowe** [comment]
> So you don't see a share link on this page @scottslowe?

Nope. I also tried starting a new conversation myself, and it doesn't show up. This is on Safari 16.6 (macOS 13.5.2). The share link shows up fine on Firefox on my system, but not in Safari.

**Comment by AaronFriel** [comment]
@scottslowe Could you take a screenshot of the developer tools for Safari, after searching for a div with the class "chat-share"?

![image](https://github.com/pulumi/pulumi-ai/assets/788800/a614c6cb-83a7-4652-84d9-75072ab73ae8)

Curious if it has a child element or not for you.

**Comment by scottslowe** [comment]
@AaronFriel Does this help?

<img width="1208" alt="Screenshot 2023-09-12 at 7 40 29 AM" src="https://github.com/pulumi/pulumi-ai/assets/1977326/21ecb2fb-09e7-4e8e-b7d4-219c07ca6bf1">

**Comment by scottslowe** [comment]
I am closing this issue. I did some more experimentation this morning and found that it was my ad blocker (AdGuard for Safari) that was blocking the Share Conversation button. I can only guess that, because of the "Share on Twitter" option, the ad blocker considers it a "social widget" and therefore blocks it. Apologies for bringing this up; I should have checked that first.
