### ISSUE TITLE
Don't use date to "generate" a random resource name

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-ai#52]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In [this conversation](https://www.pulumi.com/ai/?convid=491bfe17-1cb5-4b0d-b0ef-bd3c9c4e6256) it's using a timestamp to generate a random bucket name:

```typescript
const bucketForWebsite = new aws.s3.Bucket("websiteBucket", { 
    acl: "public-read",
    bucket: `website-bucket-${Date.now().toString()}`, // A random bucket name, real use may want a more predictable name   
    policy: JSON.stringify({
        Version: "2012-10-17",
        Statement: [
            {
                Effect: "Allow", 
                Principal: "*", 
                Action: "s3:GetObject", 
                Resource: `arn:aws:s3:::website-bucket-${Date.now().toString()}/*`, // Allow anyone to read all objects from the bucket
            }
        ]
    }),
});
```

Since we have autonaming, we don't need the `bucket` input, and probably shouldn't use a timestamp as the name anyway (if we're doing this, why not use the `RandomString` resource?

**Comment by wongstein** [comment]
I re-created the prompt here: https://www.pulumi.com/ai/conversations/b8c0a481-7b8d-40c9-9c2a-24c9ab075eae

Please let me know if this was an acceptable recreation @pierskarsenbarg

**Comment by wongstein** [comment]
Doing some early analytics, of the 42649 Typescript code blocks Pulumi.ai has created, only 63 have "date." in the code block.  Eye balling those 63, about half of them are in comments like " .. update."  About 25% are using a date function in some way, but not necessarily for naming resources.

I question if this work is necessary to fix given the very very small impact it will have
