### ISSUE TITLE
The language selector overflows its region

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-ai#55]
### What happened?

See YAML in the language selector.
<img width="1251" alt="Screenshot 2023-09-12 at 9 27 06 AM" src="https://github.com/pulumi/pulumi-ai/assets/22222529/69640ec7-0e06-4008-b003-0816655bf00a">

### Expected Behavior

Formatting is correct.

### Steps to reproduce

<img width="396" alt="Screenshot 2023-09-12 at 9 29 27 AM" src="https://github.com/pulumi/pulumi-ai/assets/22222529/7e2207d7-ca8b-4828-9a39-e992581566a2">

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cnunciato** [comment]
Fixed with https://github.com/pulumi/pulumi.ai/pull/244.
