### ISSUE TITLE
Pulumi AI reports that pulumi has no python auth0 provider

### ISSUE THREAD

**Issue by ghost** [pulumi/pulumi-ai#56]
### What happened?

https://www.pulumi.com/ai/conversations/5b371d13-d3da-4977-b661-22c47bfbd9a3

I tried to generate some code for managing auth0 resources with python. The AI reported that pulumi has no python provider for auth0 but that's not true: https://www.pulumi.com/registry/packages/auth0/
It then goes on to use dynamic providers to create a custom auth0 provider.

### Expected Behavior

It should correctly generate the code for python, as it does with typescript.

### Steps to reproduce

Use the following prompt: `I want an auth0 application called armadillo with access to the "edge" API`

### Output of `pulumi about`

I used the online pulumi AI tool.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by wongstein** [comment]
Hi, thank you for reporting this issue.  We have fixed Pulumi.ai's awareness of pulumi.auth0 package exists in Python.  
We don't have an auth0.Application resource.  In your opinion, given the Auth0 documentation (https://www.pulumi.com/registry/packages/auth0/) what resource would you have expected to fulfill your request.
