### ISSUE TITLE
Pulumi AI hallucinating on azure-native for B2CUserFlow that does not exist

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-ai#75]
### What happened?

Implementing sign-up and sign-in flows in web applications using Azure Active Directory B2C in typescript with pulumi-ai:

When using pulumi ai:  https://www.pulumi.com/ai/answers/nNwiVsC5aPm2bU7DYjiNdn/implementing-azure-ad-b2c-login-flows the following resource does not exist:
`B2CUserFlow`

### Example

The following does not exist in [azure-native:activedirectory](https://www.pulumi.com/registry/packages/azure-native/api-docs/azureactivedirectory/)
`B2CUserFlow`

// Define a user flow for sign-in and sign-up
```
const signinUserFlow = new azure_native.azureactivedirectory.B2CUserFlow("mySignInUserFlow", {
    userFlowType: "signInSignUp", // Combined sign-in and sign-up flow
    resourceGroupName: resourceGroup.name,
    userAttributes: {
        // Specify user attributes collected during sign-up
        emailAddress: true,
        givenName: true,
        surname: true,
        displayName: true,
    },
    identityProviders: {
        // Configure the identity providers for this flow
        localEmailSignUp: true, // Allow sign-up with an email address
        // Additional identity providers like Google, Facebook, etc can be added here
    },
});
```

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Thanks for reporting this @tusharshahrs, it looks like the upstream provider doesn't yet support this resource, but the underlying LLM is hallucinating a resource that _should_ exist and the cloud provider could support. We'll have this answer removed.
