### ISSUE TITLE
Pulumi AI mix between Languages 

### ISSUE THREAD

**Issue by AdiHaim** [pulumi/pulumi-ai#84]
### What happened?

I asked Pulumi-AI `add refresh to dynamic provider` and I select `Python` as my language but it won't provide answer for my request and print pulumi dynamic provider code for `JavaScript`

### Example

https://www.pulumi.com/ai/conversations/878ff2da-1804-4616-9790-2a6b00588d9d

### Output of `pulumi about`

n/a

### Additional context

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by wongstein** [comment]
Could you explain more in-depth what javascript code you received?  Additionally any detailed information on other gaps between what you expected and what you received (Such as the answer being completely wrong functionally from the cloud provider perspective) would be great too!

Thank you!
