### ISSUE TITLE
[AI Answers] Invalid answer: Hallucinating 'namespace' key in ConfigFile function.

### ISSUE THREAD

**Issue by rveder-refurb** [pulumi/pulumi-ai#96]
Affected page: https://www.pulumi.com/ai/answers/x8Be61ZQuMT1VGFLsGz3Q6/deploying-argo-cd-with-kubernetes-a-how-to-guide

**Comment by arturl** [comment]
Our work on registry overhaul will improve the situation, until then no reason to look at this one-off issue.
